//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Nullable<int> quantity { get; set; }
        public string measure { get; set; }
        public System.DateTime date_supply { get; set; }
        public System.DateTime date_expiration { get; set; }
        public double price_purchase { get; set; }
        public double price_selling { get; set; }
        public int product_id { get; set; }
        public int inventory_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
