//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ReceiptProduct
    {
        [Key, Column(Order = 0)]
        public int receipt_id { get; set; }
        [Key, Column(Order = 1)]
        public int product_id { get; set; }
        public double quantity { get; set; }
        public double price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
